# This usage of CodeQL CLI is permitted by https://securitylab.github.com/tools/codeql/license
# > Test CodeQL queries that are released under an OSI-approved Licence to confirm that new versions of those queries continue to find the right vulnerabilities.

name: Query tests

on: [push, pull_request]

jobs:
  test:
    name: Run query tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Fetch the codeql submodule
          submodules: recursive

      # Based on https://github.com/github/codeql/blob/45c942866830bec3463598774012a33a2cfaff96/.github/workflows/query-list.yml
      - name: Download CodeQL CLI
        uses: dsaltares/fetch-gh-release-asset@0.0.5
        with:
          repo: "github/codeql-cli-binaries"
          version: "latest"
          file: "codeql-linux64.zip"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Unzip CodeQL CLI
        # -q to run quietly
        run: unzip -q -d codeql-cli codeql-linux64.zip

      - name: Print CodeQL CLI version
        run: ./codeql-cli/codeql/codeql version --format=terse

      - name: Run query tests
        run: ./codeql-cli/codeql/codeql test run "--search-path=codeql:./codeql-custom-queries-java/queries" ./codeql-custom-queries-java/tests
